### ISSUE TITLE
"Cannot find module 'package.json'"; Incorrect reference when requiring package.json for default version

### ISSUE THREAD

**Issue by dhritzkiv** [webpro/versionify#10]
In the latest version (v1.0.5), the behaviour for determing a default `version` value changed to trying to accessing the package.json that's adjacent to the current file being streamed in. This is incorrect, IMO, for a few reasons.

For example, many developers have directory structures that resemble this:

```
|-- /development
    |-- /scripts
        |-- main.js
|-- package.json
```

So when the versonify module is passed in, the correct default package.json isn't found (as it is not adjacent), and this error is thrown: `Error: Cannot find module 'package.json'`

Ideally, the module would first look in the directory adjacent to the file being passed in, and then proceed to the parent directory if not found, until it is found, or until a directory no longer exists or can't be accessed.

My workaround has been to explicitly state the `version` value in the module's options.

**Comment by webpro** [comment]
I've tried a couple of things here, but I can't seem to get an error like you (unless I explicitly remove the `package.json`). I'm getting the `__VERSION__` replaced in each of the `file.js`'s:

```
.
├── dir
│   ├── dir
│   │   └── file.js
│   │   └── dir
│   │        └── file.js
│   └── file.js
│   └── index.js
└── file.js
```

Perhaps you can provide me or point me to a setup that doesn't work for you?

**Comment by dhritzkiv** [comment]
My bad! Seems I misdiagnosed the problem.

This bug happened on v1.0.5, where `version` would be calculated for _every_ file being streamed through. One of these files was a bower module (consumed in browserify using debowerify) which didn't happen to have a package.json file (it had a bower.json file, instead).

I suppose rare events where package.json doesn't exists could be handled better, but it's probably not worth it.

**Comment by webpro** [comment]
Well you've found a bug anyway, so I'll fix it soon-ish. Thanks again for your feedback.
