### ISSUE TITLE
Sourcemap support

### ISSUE THREAD

**Issue by call-a3** [webpro/versionify#11]
Just checking, but I don't think this transform comes with sourcemap support? Any chance that it could? Because right now this transform (at least I think it's this one) is messing up my debugging :/

**Comment by webpro** [comment]
It doesn't come with explicit support. How to do this?

**Comment by call-a3** [comment]
I suspect the general idea is to keep track of the position/length of the original string when you match it, and the length of the replacement string. You would then store this in a sourcemap and somehow pass it on to browserify (but how to do this exactly I'm not sure of...)

**Comment by webpro** [comment]
@call-a3 do you still think it was/is this transform is causing the issue? Maybe there's an example of a similar transform that does support source maps?

**Comment by call-a3** [comment]
I tested without this transform, and sourcemaps seem to work with versionify disabled. I'd really like to be able to use this plugin without messing up my sourcemaps...
As to how sourcemaps support is implemented in browserify plugins, I have no idea...

**Comment by webpro** [comment]
To be honest, I'm not very interested in fixing this issue. If more people face this issue or if people are willing to fix it in a PR, I'm happy to discuss it.
