### ISSUE TITLE
versionify does not resolve dependency versions.

### ISSUE THREAD

**Issue by boris-marinov** [webpro/versionify#7]
I use browserify to build a package which depends on several other packages. 
Each dependency has a different version and I use versionify with 'global':true so all version numbers are updated.

Expected:
Each package's _VERSION_ string is resolved with the package's version

Observed:
All _VERSION_ strings are resolved with the version of the package from which the build is created.

**Comment by webpro** [comment]
Closing this, since #8 was merged.
